-- public.analytics_utilisateur definition
CREATE TABLE IF NOT EXISTS public.analytics_utilisateur (
    "userID" int8 NOT NULL,
    "lastName" varchar(50) NOT NULL,
    "firstName" varchar(50) NOT NULL,
    gender varchar(50) NOT NULL,
    lon numeric(15, 3) NOT NULL,
    lat numeric(15, 3) NOT NULL,
    city varchar(50) NOT NULL,
    zip varchar(20) NOT NULL,
    state varchar(50) NOT NULL,
    registration int8 NOT NULL,
    CONSTRAINT analytics_utilisateur_pkey PRIMARY KEY ("userID")
);

-- public.analytics_song definition
CREATE TABLE IF NOT EXISTS public.analytics_song (
    "songID" int4 GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    song varchar(300) NOT NULL,
    artist varchar(300) NOT NULL,
    duration numeric(15, 2) NOT NULL,
    CONSTRAINT analytics_song_pkey PRIMARY KEY ("songID"),
    CONSTRAINT analytics_song_unique UNIQUE (song, artist)  -- Ajouter cette contrainte unique
);

-- public.analytics_session definition
CREATE TABLE IF NOT EXISTS public.analytics_session (
    "sessionID" int4 GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    ts int8 NOT NULL,
    auth varchar(50) NOT NULL,
    "level" varchar(50) NOT NULL,
    "userAgent" varchar(300) NOT NULL,
    item_in_session int4 NOT NULL,
    "userID_id" int4 NOT NULL,
    CONSTRAINT analytics_session_pkey PRIMARY KEY ("sessionID")
);
CREATE INDEX IF NOT EXISTS "analytics_session_userID_id_48213938" ON public.analytics_session USING btree ("userID_id");

-- public.analytics_session foreign keys
ALTER TABLE public.analytics_session ADD CONSTRAINT "analytics_session_userID_id_48213938_fk_analytics" FOREIGN KEY ("userID_id") REFERENCES public.analytics_utilisateur("userID") DEFERRABLE INITIALLY DEFERRED;

-- public.analytics_contenir definition
CREATE TABLE IF NOT EXISTS public.analytics_contenir (
    id int8 GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    "sessionID_id" int4 NOT NULL,
    "songID_id" int4 NOT NULL,
    CONSTRAINT analytics_contenir_pkey PRIMARY KEY (id),
    CONSTRAINT "analytics_contenir_sessionID_id_songID_id_a4ba0ea4_uniq" UNIQUE ("sessionID_id", "songID_id")
);
CREATE INDEX IF NOT EXISTS "analytics_contenir_sessionID_id_c8979ef3" ON public.analytics_contenir USING btree ("sessionID_id");
CREATE INDEX IF NOT EXISTS "analytics_contenir_songID_id_516382db" ON public.analytics_contenir USING btree ("songID_id");

-- public.analytics_contenir foreign keys
ALTER TABLE public.analytics_contenir ADD CONSTRAINT "analytics_contenir_sessionID_id_c8979ef3_fk_analytics" FOREIGN KEY ("sessionID_id") REFERENCES public.analytics_session("sessionID") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.analytics_contenir ADD CONSTRAINT "analytics_contenir_songID_id_516382db_fk_analytics_song_songID" FOREIGN KEY ("songID_id") REFERENCES public.analytics_song("songID") DEFERRABLE INITIALLY DEFERRED;
